/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'id',
    'tokenableId',
    'type',
    'name',
    'hash',
    'abilities',
    'createdAt',
    'updatedAt',
    'lastUsedAt',
    'expiresAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class BisAwardSchema extends BaseModel {
  static $columns = [
    'id',
    'competitionId',
    'catId',
    'judgeId',
    'level',
    'category',
    'sex',
    'classCode',
    'position',
    'notes',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = BisAwardSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare catId: number
  @column()
  declare judgeId: number | null
  @column()
  declare level: string
  @column()
  declare category: string | null
  @column()
  declare sex: string | null
  @column()
  declare classCode: string | null
  @column()
  declare position: number
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CatSchema extends BaseModel {
  static $columns = [
    'id',
    'competitionId',
    'registrationNumber',
    'name',
    'breed',
    'group',
    'groups',
    'class',
    'sex',
    'age',
    'exhibitorId',
    'status',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = CatSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare registrationNumber: string
  @column()
  declare name: string
  @column()
  declare breed: string
  @column()
  declare group: string
  @column()
  declare groups: any
  @column()
  declare class: string | null
  @column()
  declare sex: string | null
  @column()
  declare age: string | null
  @column()
  declare exhibitorId: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CompetitionClassSchema extends BaseModel {
  static $columns = [
    'id',
    'competitionId',
    'code',
    'name',
    'description',
    'minAgeMonths',
    'maxAgeMonths',
    'isNeuter',
    'isKittenOrJunior',
    'isSeparateBisCategory',
    'sortOrder',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = CompetitionClassSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare code: string
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column()
  declare minAgeMonths: number | null
  @column()
  declare maxAgeMonths: number | null
  @column()
  declare isNeuter: boolean
  @column()
  declare isKittenOrJunior: boolean
  @column()
  declare isSeparateBisCategory: boolean
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CompetitionGradeSchema extends BaseModel {
  static $columns = [
    'id',
    'competitionId',
    'code',
    'name',
    'countsAsAccepted',
    'eligibleForNomBis',
    'sortOrder',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = CompetitionGradeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare code: string
  @column()
  declare name: string | null
  @column()
  declare countsAsAccepted: boolean
  @column()
  declare eligibleForNomBis: boolean
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CompetitionRoleSchema extends BaseModel {
  static $columns = ['id', 'userId', 'competitionId', 'role', 'createdAt', 'updatedAt'] as const
  $columns = CompetitionRoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column()
  declare competitionId: number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CompetitionTitleSchema extends BaseModel {
  static $columns = [
    'id',
    'competitionId',
    'code',
    'name',
    'description',
    'classCodes',
    'sortOrder',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = CompetitionTitleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare code: string
  @column()
  declare name: string | null
  @column()
  declare description: string | null
  @column()
  declare classCodes: any
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CompetitionSchema extends BaseModel {
  static $columns = [
    'id',
    'name',
    'date',
    'description',
    'location',
    'status',
    'published',
    'currentRound',
    'roundsEnabled',
    'accumulatedActiveMs',
    'activeSegmentStartedAt',
    'createdById',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = CompetitionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.date()
  declare date: DateTime
  @column()
  declare description: string | null
  @column()
  declare location: string | null
  @column()
  declare status: string
  @column()
  declare published: boolean
  @column()
  declare currentRound: string | null
  @column()
  declare roundsEnabled: any | null
  @column()
  declare accumulatedActiveMs: number
  @column.dateTime()
  declare activeSegmentStartedAt: DateTime | null
  @column()
  declare createdById: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EvaluationSchema extends BaseModel {
  static $columns = [
    'id',
    'competitionId',
    'catId',
    'judgeId',
    'round',
    'grade',
    'titles',
    'position',
    'accepted',
    'nomBis',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = EvaluationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare catId: number
  @column()
  declare judgeId: number | null
  @column()
  declare round: string
  @column()
  declare grade: string | null
  @column()
  declare titles: any | null
  @column()
  declare position: number | null
  @column()
  declare accepted: boolean | null
  @column()
  declare nomBis: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventAuditLogSchema extends BaseModel {
  static $columns = [
    'id',
    'competitionId',
    'userId',
    'action',
    'entityType',
    'entityId',
    'payload',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = EventAuditLogSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number | null
  @column()
  declare userId: number | null
  @column()
  declare action: string
  @column()
  declare entityType: string | null
  @column()
  declare entityId: number | null
  @column()
  declare payload: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ExhibitorSchema extends BaseModel {
  static $columns = [
    'id',
    'competitionId',
    'name',
    'email',
    'phone',
    'userId',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = ExhibitorSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare name: string
  @column()
  declare email: string | null
  @column()
  declare phone: string | null
  @column()
  declare userId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GroupSchema extends BaseModel {
  static $columns = ['id', 'competitionId', 'name', 'sortOrder', 'createdAt', 'updatedAt'] as const
  $columns = GroupSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare name: string
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class JudgeSchema extends BaseModel {
  static $columns = [
    'id',
    'competitionId',
    'name',
    'userId',
    'stewardUserId',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = JudgeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare name: string
  @column()
  declare userId: number | null
  @column()
  declare stewardUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class JudgingOrderSchema extends BaseModel {
  static $columns = [
    'id',
    'competitionId',
    'judgeId',
    'catId',
    'orderPosition',
    'tableNumber',
    'protocolGroup',
    'protocolCallStatus',
    'ring1ProtocolCallStatus',
    'ring2ProtocolCallStatus',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = JudgingOrderSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare judgeId: number
  @column()
  declare catId: number
  @column()
  declare orderPosition: number
  @column()
  declare tableNumber: number
  @column()
  declare protocolGroup: string | null
  @column()
  declare protocolCallStatus: string
  @column()
  declare ring1ProtocolCallStatus: string
  @column()
  declare ring2ProtocolCallStatus: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NominationPhaseCompletionSchema extends BaseModel {
  static $columns = ['id', 'competitionId', 'judgeId', 'createdAt', 'updatedAt'] as const
  $columns = NominationPhaseCompletionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare judgeId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PushSubscriptionSchema extends BaseModel {
  static $columns = [
    'id',
    'userId',
    'endpoint',
    'p256Dh',
    'auth',
    'userAgent',
    'lastSeenAt',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = PushSubscriptionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column()
  declare endpoint: string
  @column()
  declare p256Dh: string
  @column()
  declare auth: string
  @column()
  declare userAgent: string | null
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class Ring1RankingCompletionSchema extends BaseModel {
  static $columns = ['id', 'competitionId', 'judgeId', 'createdAt', 'updatedAt'] as const
  $columns = Ring1RankingCompletionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare judgeId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class Ring2RankingCompletionSchema extends BaseModel {
  static $columns = ['id', 'competitionId', 'judgeId', 'createdAt', 'updatedAt'] as const
  $columns = Ring2RankingCompletionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare competitionId: number
  @column()
  declare judgeId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'id',
    'fullName',
    'email',
    'phone',
    'password',
    'role',
    'createdById',
    'isActive',
    'mustChangePassword',
    'createdAt',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string
  @column()
  declare email: string | null
  @column()
  declare phone: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column()
  declare createdById: number | null
  @column()
  declare isActive: boolean
  @column()
  declare mustChangePassword: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
